const Images = {

  profile1: require('../assets/images/Bottomicons/profile1.png'),
  profile: require('../assets/images/Bottomicons/profile.png'),
  job1: require('../assets/images/Bottomicons/job1.png'),
  job: require('../assets/images/Bottomicons/job.png'),
  contacts1: require('../assets/images/Bottomicons/contacts1.png'),
  contacts: require('../assets/images/Bottomicons/contacts.png'),
  wallet1: require('../assets/images/Bottomicons/wallet1.png'),
  wallet: require('../assets/images/Bottomicons/wallet.png'),
  notification1: require('../assets/images/Bottomicons/notification1.png'),
  notification: require('../assets/images/Bottomicons/notification.png'),
  JobIntro1:require('../assets/images/jobintro1.png'),
  JobIntro2:require('../assets/images/JobIntro2.png'),
  JobIntro3:require('../assets/images/JobIntro3.png'),
  Walkthrough1: require('../assets/images/WalkThrough1.png'),
  walletintro1: require('../assets/images/walletintro1.png'),
  walletintro2: require('../assets/images/walletintro2.png'),
  walletintro3: require('../assets/images/walletintro3.png'),
  walletintro4: require('../assets/images/walletintro4.png'),
  walletintro5: require('../assets/images/walletintro5.png'),
  walletintro6: require('../assets/images/walletintro6.png'),
  walletintroback: require('../assets/images/walletintroback.png'),
  EmptyImage: require('../assets/images/Emptyimage.png'),
  GSTModal: require('../assets/images/GSTModal.png'),
  FAQlogo: require('../assets/images/FAQlogo.png'),
  ProfileBackground: require('../assets/images/profilebackground.png'),
  UserProfilePic: require('../assets/images/userprofilepic.png'),
  Maplocation: require('../assets/images/Maplocation.png'),
  ChatIcon: require('../assets/images/chaticon.png'),
  Rederror: require('../assets/images/rederror.png'),
  profilebadge: require('../assets/images/profilebadge.png'),
  RightIcon: require('../assets/images/RightIcon.png'),
  Walkthrough2: require('../assets/images/Walkthrough2.png'),
  Walkthrough3: require('../assets/images/Walkthrough3.png'),
  Walkthrough_Next: require('../assets/images/Walkthrough_Next.png'),
  back_icon: require('../assets/images/back-ic.png'),
  BookContact: require('../assets/images/BookContact.png'),
  BlackFilter: require('../assets/images/BlackFilter.png'),
  CalnderContact: require('../assets/images/CalnderContact.png'),
  SideBar: require('../assets/images/menuIcon.png'),
  DollarIcon: require('../assets/images/DollarIcon.png'),
  LikeIcon: require('../assets/images/LikeIcon.png'),
  ClockIcon: require('../assets/images/Clockicon.png'),
  Presentationintro: require('../assets/images/Presentationintro.png'),
  Cancelicon: require('../assets/images/Cancelicon.png'),
  VideoIcon: require('../assets/images/VIdeoIcon.png'),
  Cameraicon: require('../assets/images/CameraIcon.png'),
  Gallery: require('../assets/images/gallery.png'),
  Camera: require('../assets/images/Camera.png'),
  Experienceintro: require('../assets/images/Experienceintro.png'),
  EducationIntro: require('../assets/images/EducationIntro.png'),
  LeftarrowIcon: require('../assets/images/LeftarrowIcon.png'),
  messagelisticon: require('../assets/images/messagelisticon.png'),
  qustionmarkicon: require('../assets/images/questionmarkicon.png'),
  PlusImage: require('../assets/images/PlusImage.png'),
  closeImage: require('../assets/images/closeImage.png'),
  Dobicon: require('../assets/images/dobicon.png'),
  DateImage: require('../assets/images/Dateimage.png'),
  JobCompleteProfile: require('../assets/images/JobCompleteProfile.png'),
  User: require('../assets/images/profileImage.jpeg'),
  Userdummy: require('../assets/images/user.jpg'),
  StatusUpload: require('../assets/images/StatusUpload.png'),
  Setting: require('../assets/images/setting.png'),
  Settingicon: require('../assets/images/Settingicon.png'),
  Check: require('../assets/images/Check.png'),
  Remember: require('../assets/images/Remember.png'),
  RoundCheck: require('../assets/images/RoundCheck.png'),
  RoundUnCheck: require('../assets/images/RoundUnCheck.png'),
  TermsLogo: require('../assets/images/TermsLogo.png'),
  Communicationwhite: require('../assets/images/Communicationwhite.png'),
  Communicationred: require('../assets/images/Communicationred.png'),
  jobstatuslable: require('../assets/images/jobstatuslable.png'),
  vector: require('../assets/images/Vector.png'),
  Dollar: require('../assets/images/Dollar.png'),
  Pointer: require('../assets/images/pointer.png'),
  Jobclock: require('../assets/images/Jobclock.png'),
  Jobuser: require('../assets/images/jobuser.png'),
  Joblang: require('../assets/images/joblang.png'),
  Jobcharge: require('../assets/images/jobcharge.png'),
  Jobperson: require('../assets/images/jobperson.png'),
  downArrow: require('../assets/images/downArrow.png'),
  loginlogo: require('../assets/images/loginlogo.png'),
  right: require('../assets/images/right.png'),
  left: require('../assets/images/left.png'),
  share: require('../assets/images/share.png'),
  Import: require('../assets/images/Import.png'),
  backarrow: require('../assets/images/backarrow.png'),
  blackbackarrow: require('../assets/images/blackbackarrow.png'),
  notverifedsin: require('../assets/images/notverifedsin.png'),
  pagination1: require('../assets/images/pagination1.png'),
  pagination2: require('../assets/images/pagination2.png'),
  pagination3: require('../assets/images/pagination3.png'),
  flatlist1: require('../assets/images/barroco.png'),
  joblistimage: require('../assets/images/joblistimage.png'),
  flatlist2: require('../assets/images/foiegwa.png'),
  threeDots: require('../assets/images/3_dots.png'),
  Introback: require('../assets/images/Introback.png'),
  close: require('../assets/images/close1.png'),
  mapicon: require('../assets/images/mapicon.png'),
  mapiconwhite: require('../assets/images/mapiconwhite.png'),
  Verified: require('../assets/images/Verified.png'),
  phoneicon: require('../assets/images/phoneicon.png'),
  phoneiconwhite: require('../assets/images/phoneiconwhite.png'),
  mailicon: require('../assets/images/mailicon.png'),
  Messangericon: require('../assets/images/Messangericon.png'),
  mailiconwhite: require('../assets/images/mailiconwhite.png'),
  verfiedicon: require('../assets/images/verfiedicon.png'),
  lockicon: require('../assets/images/lockicon.png'),
  AgeLockicon: require('../assets/images/AgeLockicon.png'),
  uploadicon: require('../assets/images/uploadicon.png'),
  Support: require('../assets/images/Supportiamge.png'),
  BoldMapIcon: require('../assets/images/BoldMapIcon.png'),
  BoldMailIcon: require('../assets/images/BoldMailIcon.png'),
  BoldPhoneIcon: require('../assets/images/BoldPhoneIcon.png'),
  rightCheck: require('../assets/images/rightCheck.png'),
  Mapaboutimage: require('../assets/images/mapaboutimage.png'),
  award1: require('../assets/images/award1.png'),
  award2: require('../assets/images/award2.png'),
  award3: require('../assets/images/award3.png'),
  award4: require('../assets/images/award4.png'),
  award5: require('../assets/images/award5.png'),
  award6: require('../assets/images/award6.png'),
  drawer: require('../assets/images/drawer.png'),
  Delete: require('../assets/images/Delete.png'),
  calender: require('../assets/images/calender.png'),
  facebook: require('../assets/images/facebook.png'),
  instagram: require('../assets/images/instagram.png'),
  twitter: require('../assets/images/twitter.png'),
  linkedin: require('../assets/images/linkedin.png'),
  facebookActive: require('../assets/images/facebookactive.png'),
  instagramactive: require('../assets/images/instagramactive.png'),
  twitteractive: require('../assets/images/twitteractive.png'),
  linkedinactive: require('../assets/images/linkedinactive.png'),
  alert: require('../assets/images/alert.png'),
  facebookText: require('../assets/images/facebookText.png'),
  instagramText: require('../assets/images/instagramProfile.png'),
  linkedinText: require('../assets/images/instagramText.png'),
  twitterText: require('../assets/images/twitterText.png'),
  upload: require('../assets/images/upload.png'),
  alertBlack: require('../assets/images/alertBlack.png'),
  call: require('../assets/images/call.png'),
  eyehide: require('../assets/images/eyehide.png'),
  eyeshow: require('../assets/images/PasswordEyeRight.png'),
  star: require('../assets/images/star.png'),
  map: require('../assets/images/map.png'),
  Plus: require('../assets/images/Plus.png'),
  BackgrondCheckStatusModal: require('../assets/images/BackgrondCheckStatusModal.png'),
  threeDots1: require('../assets/images/threeDot.png'),
  emailRightarrow: require('../assets/images/emailRightarrow.png'),
  mail: require('../assets/images/mail.png'),
  attachment: require('../assets/images/attachment.png'),
  backGroundCheckStatus: require('../assets/images/BackgrondCheckStatus.png'),
  add: require('../assets/images/add.png'),
  upArrow: require('../assets/images/upArrow.png'),
  backgroundAlert: require('../assets/images/backgroundAlert.png'),
  EllipseYellow: require('../assets/images/EllipseYellow.png'),
  Ellipse: require('../assets/images/Ellipse.png'),
  line: require('../assets/images/Line.png'),
  yellowCircle: require('../assets/images/yellowCircle.png'),
  Yclose: require('../assets/images/Yclose.png'),
  backgroundCheck: require('../assets/images/backgroundCheck.png'),
  quiz: require('../assets/images/quiz.png'),
  quiz1: require('../assets/images/Quiz1.png'),
  Result: require('../assets/images/Result.png'),
  Result2: require('../assets/images/Result2.png'),
  facebooklogo: require('../assets/images/Facebooklogo.png'),
  instagramlogo: require('../assets/images/instagramlogo.png'),
  twitterlogo: require('../assets/images/twitterlogo.png'),
  linkedinlogo: require('../assets/images/linkedinlogo.png'),
  SocialModalIntro: require('../assets/images/SocialModalIntro.png'),
  leftIcon: require('../assets/images/leftIcon.png'),
  moreinfo: require('../assets/images/moreinfo.png'),
  authLogo: require('../assets/images/authLogo.png'),
  key: require('../assets/images/key.png'),
  switchCamera: require('../assets/images/switchCamera.png'),
  map1: require('../assets/images/map1.png'),
  filter: require('../assets/images/filter.png'),
  play: require('../assets/images/play.png'),
  locationMarker: require('../assets/images/locationMarker.png'),
  map11: require('../assets/images/map11.png'),
  calender1: require('../assets/images/calender1.png'),
  Calendarwhite: require('../assets/images/Calendarwhite.png'),
  list1: require('../assets/images/list1.png'),
  message: require('../assets/images/message.png'),
  rightVector: require('../assets/images/rightVector.png'),
  car_yellow: require('../assets/images/carYellow.png'),
  cycle: require('../assets/images/cycle.png'),
  walk: require('../assets/images/walk.png'),
  car: require('../assets/images/car.png'),
  cycle_Yellow: require('../assets/images/yellowCycle.png'),
  walk_Yellow: require('../assets/images/yellowWalk.png'),
  calenderBlack: require('../assets/images/calanderBlack.png'),
  listBlack: require('../assets/images/listBlack.png'),
  heartIcon: require('../assets/images/heart.png'),
  heartIcon1: require('../assets/images/heart1icon.png'),
  Blocked: require('../assets/images/blocked.png'),
  Blocked1: require('../assets/images/blocked1.png'),
  right1: require('../assets/images/right1.png'),
  clock: require('../assets/images/clock.png'),
  pdf: require('../assets/images/pdf.png'),
  search: require('../assets/images/search.png'),
  skills: require('../assets/images/skills.png'),
  yellowAdd: require('../assets/images/yellowAdd.png'),
  InterViewIntro: require('../assets/images/InterViewIntro.png'),
  circelYellow: require('../assets/images/yellowCircel.png'),
  calenderIcon: require('../assets/images/calenderIcon.png'),
  ReferenceLogo: require('../assets/images/ReferenceLogo.png'),
  ReferenceItem: require('../assets/images/ReferenceItem.png'),
  ConsentreferenceLogo: require('../assets/images/ConsentreferenceLogo.png'),
  ReferenceItem2: require('../assets/images/ReferenceItem2.png'),
  gps: require('../assets/images/gps.png'),
  grayMarker: require('../assets/images/grayMarker.png'),
  bus: require('../assets/images/bus.png'),
  bed: require('../assets/images/bad.png'),
  food: require('../assets/images/food.png'),
  money: require('../assets/images/money.png'),
  File_dock: require('../assets/images/File_dock.png'),
  uploadInactive:require('../assets/images/uploadInactive.png'),
  redCross:require('../assets/images/redCross.png'),
  maplawyer:require('../assets/images/map_lawyer.png'),
  cameraYellow:require('../assets/images/cameraYellow.png'),
  File_dock_yellow:require('../assets/images/File_dock_yellow.png'),
  EditText:require('../assets/images/EditText.png'),
  RemoveVideo:require('../assets/images/RemoveVideo.png'),
  videoposter:require('../assets/images/videoposter.png'),
  videoposter2:require('../assets/images/videoposter2.png'),
  videoposter3:require('../assets/images/videoposter3.jpg'),
  PlayerIcon:require('../assets/images/PlayerIcon.png'),
  Finalnotice:require('../assets/images/Finalnotice.png'),
  ExperinceImage:require('../assets/images/ExperinceImage.png'),
  ConsentMain:require('../assets/images/ConsentMain.png'),
  CertificationLogo:require('../assets/images/CertificationLogo.png'),
  CertificationListLogo:require('../assets/images/CertificationListLogo.png'),
  GoodNews:require('../assets/images/GoodNews.png'),
  Educationlistlogo:require('../assets/images/Educationlistlogo.png'),
  skilllogo:require('../assets/images/skilllogo.png'),
  FoodService:require('../assets/images/FoodService.png'),
  cleaning:require('../assets/images/cleaning.png'),
  Downloadpdf:require('../assets/images/Downloadpdf.png'),
};

export default Images;
