
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'StaffRenter' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'StaffRenterTests' do
    inherit! :complete
    # Pods for testing
  end

use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
post_install do |installer|

  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
end
