import {StyleSheet, Platform} from 'react-native';
import {width, height} from '../../../../constants/ScreenSize';
import colors from '../../../../constants/colors';
import fonts from '../../../../constants/fonts';
import fontsize from '../../../../constants/i18n/Fontsizes';
const styles = StyleSheet.create({
  buttonStyle: {
    backgroundColor: colors.yellow,
    height: width * (26 / 375),
    width: width * (58 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  title: {
    fontFamily: fonts.SemiBold,
    fontSize: width * (16 / 375),
  },

  buttonTextStyle: {
    fontSize: width * (16 / 375),
    color: colors.inputTitle,
  },
  buttonTextBook: {
    fontSize: width * (16 / 375),
    color: colors.yellow,
  },

  viewstyle: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: width * (30 / 375),
    marginBottom: width * (7 / 375),
    paddingHorizontal: width * (22 / 375),
    height: width * (50 / 375),
    marginBottom: width * (15 / 375),
  },
  pickerView: {
    flex: 1,
    paddingHorizontal: width * (20 / 375),
    fontSize: fontsize.Regular,
    color: colors.textinputColor,
    width: width * (90 / 375),
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: 30,
    shadowColor: colors.shadowColor,
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
  },

  viewstyle1: {
    flex: 0.1,
    alignItems: 'center',
  },

  touchableStyle: {
    height: width * (20 / 375),
    width: width * (20 / 375),
    borderRadius: width * (20 / 375),
    borderColor: colors.checkbox,
    borderWidth: width * (2 / 375),
    padding: width * (2 / 375),
  },

  viewStyle2: {height: '100%', width: '100%', borderRadius: width * (20 / 375)},

  viewstyle3: {
    flex: 0.8,
    alignItems: 'center',
  },

  buttonStyle1: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (150 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonStyle2: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonStyleBook: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: width * (30 / 375),
  },
  buttonStyleBook12: {
    backgroundColor: colors.white,
    height: width * (50 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: width * (30 / 375),
    borderColor: colors.yellow,
    borderWidth: 1,
  },
  buttonStyleBook13: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: width * (30 / 375),
  },

  language: {
    paddingHorizontal: width * (15 / 375),
    fontSize: fontsize.Regular,
    color: colors.textinputColor,
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    width: width * (300 / 375),
    height: width * (50 / 375),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  image1: {position: 'absolute', right: 10, top: 20, zIndex: 9999},

  errorText: {
    marginTop: width * (10 / 375),
    color: colors.red,
  },

  profileImage: {
    height: width * (93 / 375),
    width: width * (93 / 375),
    borderRadius: width * (93 / 375),
    alignSelf: 'center',
    backgroundColor: colors.whitebackground,
  },

  headingText: {
    alignSelf: 'center',
    marginBottom: width * (30 / 375),
    fontSize: fontsize.Extralarge,
    lineHeight: width * (44 / 375),
  },

  errorText12: {
    fontSize: fontsize.Regular,
    fontStyle: 'normal',
  },

  backgroundVideo: {
    height: width * (200 / 375),
  },

  container: {backgroundColor: colors.whitebackground, flex: 1},

  view1: {
    paddingHorizontal: width * (15 / 375),
    paddingVertical: width * (20 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: width * (20 / 375),
    marginHorizontal: width * (15 / 375),
    borderRadius: width * (15 / 375),
    marginBottom: width * (18 / 375),
  },

  view2: {
    paddingHorizontal: width * (15 / 375),
    paddingVertical: width * (10 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: width * (20 / 375),
    marginHorizontal: width * (15 / 375),
    borderRadius: width * (15 / 375),
    marginBottom: width * (18 / 375),
  },

  image: {
    width: width * (80 / 375),
    height: width * (80 / 375),
    marginVertical: width * (5 / 375),
    borderRadius: width * (110 / 375),
  },

  view3: {flexDirection: 'row', justifyContent: 'center'},

  view4: {
    paddingHorizontal: width * (15 / 375),
    paddingVertical: width * (10 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: width * (20 / 375),
    marginHorizontal: width * (15 / 375),
    borderRadius: width * (15 / 375),
    marginBottom: width * (18 / 375),
  },

  Touch1: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: width * (30 / 375),
    borderWidth: width * (0.5 / 375),
    height: width * (36 / 375),
    width: width * (200 / 375),
    borderColor: colors.gray3,
  },

  text1: {
    textAlign: 'center',
    marginVertical: width * (10 / 375),
    fontSize: width * (10 / 375),
    fontFamily: fonts.Regular,
  },

  view5: {
    backgroundColor: colors.whitebackground,
    padding: width * (15 / 375),
    borderTopLeftRadius: width * (30 / 375),
    borderTopRightRadius: width * (30 / 375),
    alignItems: 'center',
  },
  button32: {
    backgroundColor: colors.yellow,
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: width * (20 / 375),
    marginBottom: '7%',
    width: width * (150 / 375),
  },
  view33: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  view34: {
    borderWidth: 1,
    borderRadius: 15,
    borderColor: colors.grayborder,
    marginTop: 20,
    height: height / 2 + 50,
  },
  view35: {
    alignSelf: 'center',
    marginTop: width * (5 / 375),
    fontWeight: 'bold',
  },
  view36: {
    backgroundColor: colors.white,
    borderTopLeftRadius: width * (20 / 375),
    borderTopRightRadius: width * (20 / 375),
    paddingHorizontal: width * (25 / 375),
    paddingTop: width * (25 / 375),
    marginBottom: width * (30 / 375),
  },
  view37: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.modelBackground,
  },
  view38: {
    textAlign: 'center',
    marginBottom: width * (30 / 375),
  },
  view39: {
    textAlign: 'center',

    marginBottom: width * (15 / 375),
    color: colors.yellow,
  },
  view40: {
    textAlign: 'center',

    marginBottom: width * (3 / 375),
    color: colors.yellow,
  },
  view41: {
    textAlign: 'center',

    marginVertical: width * (20 / 375),
  },
  view42: {
    textAlign: 'center',

    marginVertical: width * (10 / 375),
  },
  view43: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (15 / 375),
  },
  view44: {
    backgroundColor: colors.white,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view45: {
    backgroundColor: 'rgba(255,255,355,0.6)',

    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: width * (15 / 375),
    paddingBottom: width * (10 / 375),
  },
  view46: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: width * (20 / 375),
  },
  view47: {
    textAlign: 'center',

    marginBottom: width * (30 / 375),
  },
  view48: {
    textAlign: 'center',

    marginBottom: width * (15 / 375),
    color: colors.yellow,
  },
  view49: {
    textAlign: 'center',

    marginBottom: width * (3 / 375),
    color: colors.yellow,
  },
  view50: {
    textAlign: 'center',

    marginBottom: width * (10 / 375),
  },
  view51: {
    textAlign: 'center',
    marginTop: width * (10 / 375),
    marginBottom: width * (30 / 375),
  },
  view52: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (15 / 375),
  },
  view53: {
    backgroundColor: colors.white,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view54: {
    backgroundColor: 'rgba(255,255,355,0.6)',

    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: width * (15 / 375),
    paddingBottom: width * (10 / 375),
  },
  view55: {
    color: 'red',
    fontSize: fontsize.Small,
    lineHeight: width * (18 / 375),
    marginBottom: width * (20 / 375),
    paddingHorizontal: width * (10 / 375),
  },
  view56: {
    borderRadius: width * (30 / 375),
    borderWidth: 1,
    borderColor: colors.modelBackground,
    height: width * (60 / 375),
    marginVertical: width * (15 / 375),
    justifyContent: 'center',
    paddingHorizontal: width * (20 / 375),
  },
  view57: {
    marginVertical: width * (25 / 375),
    textAlign: 'center',
  },
  view58: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (15 / 375),
  },
  view59: {
    backgroundColor: colors.white,

    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view60: {
    backgroundColor: 'rgba(255,255,355,0.6)',

    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: width * (15 / 375),
    paddingVertical: width * (25 / 375),
  },
  view61: {
    backgroundColor: colors.yellow,
    height: width * (40 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },
  view62: {
    marginHorizontal: width * (15 / 375),
    marginVertical: 30,
    alignItems: 'center',
  },
  view63: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 30,
    alignItems: 'center',
    height: width * (50 / 375),
  },
  view64: {
    color: colors.gray,
    width: '100%',

    paddingLeft: width * (10 / 375),
  },
  view65: {
    height: 50,
    backgroundColor: 'white',
    marginTop: width * (20 / 375),
    marginBottom: width * (15 / 375),
    borderRadius: width * (30 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * (20 / 375),
  },
  view66: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (10 / 375),
  },
  view67: {
    backgroundColor: colors.whitebackground,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
  },
  view68: {
    backgroundColor: colors.yellow,
    height: width * (40 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },
  view69: {
    marginHorizontal: width * (15 / 375),
    marginVertical: 30,
    alignItems: 'center',
  },
  view70: {
    height: 50,
    backgroundColor: 'white',
    marginTop: width * (20 / 375),
    marginBottom: width * (15 / 375),
    borderRadius: width * (30 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * (20 / 375),
  },
  view71: {
    backgroundColor: colors.yellow,
    height: width * (40 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },
  view72: {
    marginHorizontal: width * (15 / 375),
    marginVertical: 30,
  },
  view73: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems: 'center',
    height: width * (50 / 375),
  },
  view74: {
    backgroundColor: colors.whitebackground,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view75: {
    backgroundColor: colors.yellow,
    height: width * (40 / 375),
    width: width * (120 / 375),
    borderRadius: width * (25 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },
  view76: {
    marginHorizontal: width * (15 / 375),
    marginVertical: 30,
  },
  view77: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems: 'center',
    height: width * (50 / 375),
  },
  view78: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (10 / 375),
  },
  view79: {
    backgroundColor: colors.whitebackground,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view80: {
    paddingHorizontal: width * (15 / 375),
  },
  view81: {
    color: colors.primary,
    fontSize: 15,
    padding: 15,
  },
  view82: {
    alignSelf: 'flex-start',
    marginTop: width * (5 / 375),
    marginLeft: width * (10 / 375),
  },
  view83: {
    backgroundColor: colors.white,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view84: {
    height: width * (30 / 375),
    width: width * (30 / 375),
    alignSelf: 'flex-end',
    marginBottom: width * (10 / 375),
  },
  view85: {
    borderRadius: width * (8 / 375),
    borderColor: '#FDBF5A',
    borderWidth: 2,
  },
  view86: {
    backgroundColor: 'rgb(255,255,255)',

    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: width * (15 / 375),
  },
  view87: {
    borderWidth: 0.5,
    borderColor: colors.gray3,
    flexDirection: 'row',
    borderRadius: 10,
    padding: 15,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  view88: {
    color: colors.yellow,
    textAlign: 'center',
    marginVertical: width * (8 / 375),
  },
  view89: {
    paddingHorizontal: width * (75 / 375),
    paddingVertical: width * (20 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: 20,
    marginHorizontal: width * (15 / 375),
    borderRadius: width * (25 / 375),
    marginBottom: width * (18 / 375),
  },
  view90: {
    marginTop: width * (2 / 375),
    color: 'red',
    fontSize: fontsize.Small,
  },
  view91: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: width * (30 / 375),
    borderWidth: 0.5,
    height: width * (36 / 375),
    width: width - 80,
    marginTop: width * (30 / 375),
    borderColor: colors.gray3,
  },
  view92: {
    alignSelf: 'flex-start',
    marginTop: width * (5 / 375),
    marginLeft: width * (10 / 375),
  },
  view93: {
    backgroundColor: colors.white,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  view94: {
    paddingHorizontal: width * (15 / 375),
  },
  view95: {
    position: 'absolute',
    top: width * (18 / 375),
    zIndex: 999,
  },
  view96: {
    flex: 0.8,
    backgroundColor: colors.whitebackground,
    borderRadius: 30,
    paddingTop: width * (28 / 375),
  },
  view97: {flex: 0.2, marginHorizontal: width * (15 / 375)},
  view98: {
    height: height - 200,
    backgroundColor: colors.whitebackground,
    borderRadius: 30,
    paddingTop: width * (28 / 375),
  },
  view99: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  view100: {
    backgroundColor: colors.modelBackground,
    flex: 1,
    paddingHorizontal: width * (10 / 375),
    justifyContent: 'center',
  },
  view101: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems: 'center',
    height: width * (50 / 375),
  },
  view102: {
    marginTop: width * (10 / 375),
    marginHorizontal: width * (20 / 375),
    color: colors.red,
  },
  view103: {
    width: width * (300 / 375),
    marginTop: width * (10 / 375),
  },
  view104: {
    marginVertical: width * (10 / 375),

    color: colors.red,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginHorizontal: width * (25 / 375),
  },
  view105: {
    position: 'absolute',
    right: 10,
    top: 20,
    zIndex: 9999,
  },
  view106: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  view107: {
    fontSize: fontsize.Small,
    color: colors.red,

    marginTop: width * (10 / 375),
  },
  view108: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (10 / 375),
  },
  view109: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems: 'center',
    height: width * (50 / 375),
  },
  view110: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    marginBottom: width * (30 / 375),
  },
  view111: {
    width: width * (300 / 375),
    marginTop: width * (10 / 375),
  },
  view112: {
    marginTop: width * (10 / 375),
    marginHorizontal: width * (20 / 375),
    color: colors.red,
  },
  view113: {
    marginVertical: width * (10 / 375),

    color: colors.red,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginHorizontal: width * (25 / 375),
  },
  view114: {
    position: 'absolute',
    right: 10,
    top: 20,
    zIndex: 9999,
  },
  view115: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: width * (15 / 375),
    paddingTop: width * (25 / 375),
    paddingBottom: width * (15 / 375),
  },
  view116: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  view117: {
    flex: 0.6,
    paddingRight: width * (5 / 375),
    paddingLeft: width * (10 / 375),
  },
  view118: {
    flex: 0.8,
    paddingRight: width * (5 / 375),
    paddingLeft: width * (10 / 375),
  },
  view119: {
    flex: 0.1,
    height: width * (30 / 375),
    justifyContent: 'center',
  },
  view120: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  view121: {
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (10 / 375),
  },
  view122: {
    flex: 0.2,

    color: colors.yellow,
  },
  view123: {
    flex: 0.6,
    paddingRight: width * (5 / 375),
    paddingLeft: width * (10 / 375),
  },
  view124: {
    flex: 0.1,
    height: width * (30 / 375),

    justifyContent: 'center',
  },
  view125: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  presentationbutton: {
    backgroundColor: colors.yellow,
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: width * (20 / 375),
    marginBottom: '12%',
    width: '95%',
  },
  commmontext: {
    textAlign: 'center',
    margin: width * (10 / 375),
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
  },
  timefor: {
    fontFamily: fonts.Bold,
    alignSelf: 'center',
    fontSize: fontsize.Regular,
    marginBottom: 10,
  },
  objective: {
    textAlign: 'center',
    margin: width * (10 / 375),
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
  },
  appointmentwith: {
    textAlign: 'center',
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
    margin: width * (15 / 375),
    marginHorizontal: 20,
  },
  thumbnailImage: {
    height: 250,
    position: 'absolute',
    width: '99%',
    borderRadius: 20,
  },
  thumbnailImageview: {
    position: 'absolute',
    justifyContent: 'center',
    alignSelf: 'center',
    top: 130,
  },
  RemoveVideo: {
    zIndex: 1,
    position: 'absolute',
    right: 50,
    top: 10,
    width: 30,
    height: 30,
  },
  buttonmain: {
    width: '100%',
    justifyContent: 'space-around',
    flexDirection: 'row',
    marginVertical: width * (10 / 375),
  },
  buttonstyle: {
    flexDirection: 'row',
    borderRadius: width * (30 / 375),
    height: width * (40 / 375),
    width: width * (170 / 375),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  buttonstyle2: {
    flexDirection: 'row',
    borderRadius: width * (30 / 375),
    height: width * (40 / 375),
    width: width * (170 / 375),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderColor: colors.yellow,
  },
  view130: {
    flex: 0.6,
    paddingRight: width * (5 / 375),
    paddingLeft: width * (10 / 375),
  },
  view131: {
    flex: 0.1,
    height: width * (30 / 375),

    justifyContent: 'center',
  },
  view132: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  view133: {
    flex: 0.6,
    paddingRight: width * (5 / 375),
    paddingLeft: width * (10 / 375),
  },
  view134: {
    flex: 0.1,
    height: width * (30 / 375),

    justifyContent: 'center',
  },
  view135: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  view136: {
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (10 / 375),
  },
  view137: {
    flex: 1,
    paddingHorizontal: width * (15 / 375),
    flexDirection: 'row',
    alignItems: 'center',
    color: colors.textinputColor,
    fontSize: fontsize.Regular,
    height: width * (50 / 375),
    backgroundColor: colors.white,
    borderRadius: width * (30 / 375),
    borderWidth: Platform.OS == 'android' ? 2 : 0,
    borderColor: 'rgba(253, 191, 90, 0.35)',
    shadowColor: 'rgba(253, 191, 90, 0.35)',
    shadowOpacity: 10,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    marginHorizontal: width * (15 / 375),
    marginBottom: width * (15 / 375),
  },
  view138: {
    backgroundColor: colors.lightYellow,
    height: width * (50 / 375),
    width: width * (150 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: width * (1 / 375),
    borderColor: colors.yellow,
  },
  view139: {
    backgroundColor: colors.lightYellow,
    height: width * (50 / 375),
    width: width * (150 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: width * (1 / 375),
    borderColor: colors.yellow,
  },
  view140: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (150 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  view141: {
    position: 'absolute',
    right: 10,
    top: 5,
    backgroundColor: colors.white,
    padding: 5,
    borderRadius: width * (20 / 375),
  },
  view142: {
    marginTop: width * (20 / 375),
    justifyContent: 'center',
    marginHorizontal: width * (25 / 375),
    marginBottom: width * (15 / 375),

    alignSelf: 'center',
    backgroundColor: colors.white,
  },
  view143: {
    marginLeft: width * (15 / 375),
    height: width * (20 / 375),
    width: width * (20 / 375),
  },
  view144: {
    paddingHorizontal: width * (15 / 375),
    paddingVertical: width * (10 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: 20,
    marginHorizontal: width * (15 / 375),
    borderRadius: width * (15 / 375),
    marginVertical: width * (20 / 375),
  },
  view145: {
    width: width * (70 / 375),
    resizeMode: 'contain',
  },
  mediaPlayerFull: {
    backgroundColor: colors.black,
    borderRadius: width * (15 / 375),
    flex: 1,
  },
});

export default styles;
