import {StyleSheet} from 'react-native';
import {width} from '../../../../constants/ScreenSize';
import colors from '../../../../constants/colors';
import fonts from '../../../../constants/fonts';
import fontsize from '../../../../constants/i18n/Fontsizes';
const styles = StyleSheet.create({
  buttonStyle: {
    backgroundColor: colors.yellow,
    height: width * (36 / 375),
    width: width * (108 / 375),
    borderRadius: width * (18 / 375),
  },
  title: {
    fontFamily: fonts.SemiBold,
    fontSize: width * (16 / 375),
  },

  buttonTextStyle: {
    fontSize: 16,
    color: colors.inputTitle,
  },
  buttonTextStyle12: {
    fontSize: 16,
    color: colors.red,
  },
  add: {flexDirection: 'row', justifyContent: 'center'},

  viewstyle: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: width * (30 / 375),
    marginBottom: width * (7 / 375),
    paddingHorizontal: width * (22 / 375),
    height: width * (50 / 375),
    marginBottom: 15,
  },
  viewstyle1: {
    flex: 0.1,
    alignItems: 'center',
  },
  touchableStyle: {
    height: width * (20 / 375),
    width: width * (20 / 375),
    borderRadius: width * (20 / 375),
    borderColor: colors.checkbox,
    borderWidth: 2,
    padding: 2,
  },
  viewStyle2: {height: '100%', width: '100%', borderRadius: width * (20 / 375)},
  viewstyle3: {
    flex: 0.8,
    alignItems: 'center',
  },
  buttonStyle1: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (150 / 375),
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonStyle12: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (220 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: width * (20 / 375),
  },
  button_Style: {
    backgroundColor: colors.lightRed,
    height: width * (50 / 375),
    width: width * (220 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.red,
  },
  buttonStyle2: {
    backgroundColor: colors.yellow,
    height: width * (50 / 375),
    width: width * (120 / 375),
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },

  language: {
    flex: 1,

    paddingHorizontal: width * (15 / 375),
    fontSize: fontsize.Regular,
    color: colors.textinputColor,

    backgroundColor: colors.white,
    borderRadius: 30,
    width: width * (300 / 375),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  image1: {position: 'absolute', right: 10, top: 20, zIndex: 9999},
  errorText: {
    marginTop: width * (10 / 375),

    color: colors.red,
  },
  profileImage: {
    height: width * (93 / 375),
    width: width * (93 / 375),
    borderRadius: width * (93 / 375),
    alignSelf: 'center',

    backgroundColor: colors.whitebackground,
  },
  headingText: {
    alignSelf: 'center',
    fontSize: fontsize.Large,
    fontFamily: fonts.Bold,
    marginBottom: 20,
  },
  errorText12: {
    fontSize: fontsize.Regular,
    fontStyle: 'normal',
  },
  _rendernotiListsview: {
    width: '100%',
          alignItems: 'center',
          flexDirection: 'row',
          backgroundColor: '#fff',
          borderTopWidth: 1,
          borderTopColor: '#ececec',
          justifyContent: 'space-around',
  },
  commonstatus: {
    borderWidth: 0.5,
    width: '100%',
    height: 35,
    borderRadius: 30,
    marginRight: width * (20 / 375),
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteimg: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    right: 50,
  },
  willreferencestext: {
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 10,
    fontFamily: fonts.Bold,
    fontSize: fontsize.Regular,
  },
  got_it2: {
    backgroundColor: colors.yellow,
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: width * (10 / 375),
    marginBottom: width * (40 / 375),
    width: '50%',
  },
  Goodnewstext: {
    alignSelf: 'center',
    fontSize: 24,
    marginVertical: 5,
    fontFamily: fonts.Bold,
  },
  closeimg: {
    flexDirection: 'row',
    height: width * (40 / 375),

    alignItems: 'center',
    width: width * (50 / 375),
    justifyContent: 'space-between',
    marginVertical: '3%',
  },
  goodnewsModalview: {
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
    borderRadius: 20,
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: width * (20 / 375),
    paddingHorizontal: width * (20 / 375),
  },
  Got_it5: {
    backgroundColor: colors.yellow,
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',

    marginBottom: '7%',
    width: '100%',
  },
  htmlmain: {
    backgroundColor: colors.white,
    borderRadius: width * (20 / 375),
    padding: width * (18 / 375),
    marginTop: width * (10 / 375),
    borderWidth: 0.5,
    borderColor: colors.grayborder,
    height: 300,
  },
  Detailstext: {
    fontFamily: fonts.Bold,
    marginVertical: 10,
    fontSize: fontsize.Regular,
    marginHorizontal: 10,
  },
  renderitem1: {
    borderRadius: width * (10 / 375),
    padding: width * (15 / 375),
    backgroundColor: colors.whitebackground,
    marginTop: width * (20 / 375),
    marginHorizontal: width * (15 / 375),
  },

  style11: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (10 / 375),
  },
  style12: {
    backgroundColor: colors.whitebackground,
    padding: width * (20 / 375),
    borderRadius: width * (30 / 375),
    alignItems: 'center',
  },
  style13: {
    backgroundColor: colors.whitebackground,

    marginHorizontal: width * (15 / 375),
    borderRadius: width * (15 / 375),

    marginTop: width * (5 / 375),
    width: '95%',
  },
  style14: {
    alignSelf: 'flex-start',
    marginTop: width * (25 / 375),
    marginLeft: width * (10 / 375),
  },
  style15: {
    backgroundColor: colors.whitebackground,
    padding: width * (15 / 375),
    borderRadius: width * (30 / 375),
  },
  style16: {
    borderWidth: 1,
    height: width * (28 / 375),
    width: width * (70 / 375),
    borderRadius: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
  },
  previousexperiences: {
    textAlign: 'center',
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
  },
  Addexperiencebuttonview: {
    paddingHorizontal: width * (15 / 375),
    paddingBottom: 5,
    borderBottomColor: colors.gray,
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginVertical: width * (10 / 375),
  },
  Addexperiencebutton: {
    flexDirection: 'row',
    borderRadius: width * (30 / 375),
    height: width * (40 / 375),
    width: width * (170 / 375),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  addexpheading: {
    fontSize: fontsize.Large,
    fontFamily: fonts.Bold,
    alignSelf: 'center',

    marginBottom: width * (10 / 375),
  },
  Addreference: {
    backgroundColor: colors.yellow,
    position: 'absolute',
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    width: '95%',
  },
  pickerview: {
    borderBottomColor: colors.yellow,
    borderBottomWidth: 1,
    flex: 1,
    justifyContent: 'center',
    fontSize: fontsize.Regular,
    color: colors.textinputColor,
    marginHorizontal: 15,
    marginBottom: 8,
    paddingBottom: 15,
  },
  downArrowimg: {
    position: 'absolute',
    right: 15,
    bottom: 17,
    alignSelf: 'flex-end',
  },
  Selectpasttext: {
    marginTop: 5,
    marginLeft: 20,
    fontFamily: fonts.Regular,
  },
  Confirmbutton: {
    position: 'absolute',
    borderRadius: 30,
    height: width * (50 / 375),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '7%',
    width: '100%',
  },
  TPositionview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
    marginHorizontal: 15,
  },
  usingpeopletext: {
    textAlign: 'center',
    marginVertical: width * (20 / 375),
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
    lineHeight: 25,
  },
  betterprofiletext: {
    fontFamily: fonts.Bold,
    alignSelf: 'center',
    fontSize: fontsize.Regular,
    marginTop: 20,
  },
  morereferencestext: {
    textAlign: 'center',
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
    lineHeight: 25,
  },
  Referencesaretext: {
    textAlign: 'center',
    marginTop: 20,
    fontFamily: fonts.Regular,
    fontSize: fontsize.Regular,
    lineHeight: 25,
  },
  Buttonview: {
    backgroundColor: 'white',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    height: 100,
    width: '100%',
  },
});

export default styles;
